### ISSUE TITLE
UE 5.3 The following modules are missing or built with a different engine version. Engine modules cannot be compiled at runtime

### ISSUE THREAD

**Issue by ricardopald** [cem-akkaya/LightAwareness#3]
Hi,
I get the following error while trying to add the plugin to my project in UE 5.3

> The following modules are missing or built with a different engine version:
> 
>   LightAwareness
> 
> Engine modules cannot be compiled at runtime. Please build through your IDE.

Steps to reproduce:
1.- Download LightAwarness 1.0.1 from Github
2.- Place LightAwareness Plugin under : Drive:\UE\Engine\Plugins\Marketplace\LightAwareness
3.- Activate the plugin in your project plugins
4.- Reopen the project
5.- Project says that LightAwarness was built for UE 5.4 accept
6.- This error appears saying that the module cannot be built

**Comment by cem-akkaya** [comment]
Hello, recommended version is 5.4 however you can use in 5.3

Please Re-Download the project from 

1. https://github.com/cem-akkaya/LightAwareness/archive/refs/heads/master.zip
2. Place your project under plugins not in Engine -  Drive:\YOURPROJECT\Plugins\LightAwareness\
3. Rebuild your project from IDE - I feel that your project is blurprint only, if so you may have to convert it to a Source Code Project.
4. If you get errors regarding materials you have to download [this](https://www.cemakkaya.com/FileHost/LightAwarenessContentFallback.zip) and place them under your plugin folder.

**Comment by ricardopald** [comment]
Yep this fixed the issue, thanks!
