### ISSUE TITLE
Light Awareness component usability extension.

### ISSUE THREAD

**Issue by cem-akkaya** [cem-akkaya/LightAwareness#5]
1.  As a designer I would like to provide return owner variables to component as well as tags to improve identification in large systems.
2. As a designer I would like to make a mini gameinstance subsystem for registering and deregistering components on runtime so that users can access light provider components with ease.

### Discussed in https://github.com/cem-akkaya/LightAwareness/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **r0b3rtf1sh3r** October 15, 2024</sup>
thank you for creating this, it fit my needs perfectly for detecting light levels driving "solar panel" regeneration style effect in my game
easily just added to plugins folder. configured variables. and debug readings to adjust factors. and BAM
works perfectly. 

one suggestion. perhaps include a way to determine which actor is checked for light. that way you could check the collision capsule or any other thing instead of character/actor =) </div>

**Comment by r0b3rtf1sh3r** [comment]
Awesome. yeah i was going to ask about the component tag. 
this is a tag you provide to any instanced actor in the scene to be registered (even if not contributing to GI or visible on screen) will be registered?

atm im just using global illumination thru lumen driving the light level.
its practically turns my mesh into a light meter its great. 
i have it running on a timer by event at 0.25 sec looping while active. 
also a "just bottom" direction would be awesome to. practicality probably calls for integration into physical materials,
this functionality would syncronize with line traces for stuff like determining phys material. (under feet,touching/overlap etc)
this way you can compare both of them. get the materials add them to a preliminary array, create a 2nd array of the same and set them as a temporary "dynamic" material. this way you can update the "light meter aka light awareness component" from the same event/call =) 

idk just some idea. i was totally blindsided by this plugin. its the coolest thing since sliced bread.

**Comment by r0b3rtf1sh3r** [comment]
Let me know if there is any testing or help i can provide in facilitating this =)

**Comment by cem-akkaya** [comment]
Sure think I can add couple of more flex option to component itself like render only down. (tbh I though there won't be any use cases for it but here we are).

Can add couple of states to component like 
Registered
RegisteredRecentlyRendered
Unregistered

Recently rendered is quite cost efficient method to know if the object is visible or not. Otherwise the plugin will scope up to a scanner/targeting system if we want the object to be providing distance angle to the source (player). Tbh depends on the use cases, having that on the component by default would be imo costly for many other users of the plugin however RecentlyRendered can be implemented easyly. 

Tag wise I was thinking the LightAwarenessComponent:GetObjectName which would be uniqie string where you can always strip from ":" and get ObjectID if you need to do further identification.However in subsystem we can already save them actorcomponentArray->component->State etc

but if you have a use case that you need to fast find a specific object in that array (not sure how many objects can be around you at a single time let's say 500) On that cases TMap can be better since you can search for specific item on the map more faster. Lets say the ones that are in StateOf: RegisteredRecentlyRendered

Let me know your toughts. I am in the middle of something else that I can not context switch right now but as soon as I do that a bit, will make sure of some improvements get implemented to LightAwareness.

**Comment by cem-akkaya** [comment]
hi made some changes

-General refactors
-Component adds tag with owner name identification both to component and owner actor
-Component has Inactive, Active and Active Rendering States
-Component can check its owners rendering state and define component state
-Component settings refactor for is valid asset state checks
-Optimise and briefly refactor GetBufferPixels()
-Possibility to only render bottom directional light status
-Subsystem addition providing possibility to mass scale get light awareness responders, their status and register unregister events.

Let me know if these additions are beneficial for you and imrpoves the overall ux of the lightawareness. 

Let me know what you think and if you need something specific.

Cem

**Comment by r0b3rtf1sh3r** [comment]
ill try the new version thanks for making these changes, you're amazing,
(bug submit below)
I was noticing a weird hitch when i use the component on a player character, and is moving, (regardless of size location)
will hitch every 0.5-1 second. u can see a visual stutter. also tried lowering the tick from 0.01 to 0.1 and 0.5 and 1 etc
i have a check that runs every 1 second when it is in use. originally 0.25 sec  but unsure as it wasnt noticed at first.
any idea what to check?

**Comment by cem-akkaya** [comment]
Not at all not sure what hitch is: can you describe what is happening in detail or its like stutter hiccup?

if so what is cpu specs and your current fps in game and how many components are running at a given time?

**Comment by r0b3rtf1sh3r** [comment]
perhaps ill upload a video, this my first year using unreal, perhaps you may spot something.

**Comment by r0b3rtf1sh3r** [comment]
sorry for delay here is a video
i have a print string (top right) shows value currently of light as float. 
on delay timer every 0.25 ill post screens below of my logic
here is video highlighting the microstutter when plugin is enabled 

https://vimeo.com/1026089545?share=copy

**Comment by r0b3rtf1sh3r** [comment]
[image](https://github.com/user-attachments/assets/c7e17cc4-d57c-4c40-b8c9-4ae2bd044ee0)
this is on begin play and paused.

**Comment by r0b3rtf1sh3r** [comment]
![image](https://github.com/user-attachments/assets/7bbc59ef-f7ae-45b8-8cdb-f707558edddf)

here is the logic. 
breakdown; (check if in sunlight (or artificial light) for different regen rates build on light value %threshold value x regen rate))
pause energy refill if under threshold. delay , notify/dispatch and delay on completed (currently unplugged for debug testing)

**Comment by r0b3rtf1sh3r** [comment]
![image](https://github.com/user-attachments/assets/d1d7b2f2-ab14-4903-afcc-9b88ba0eddef)

i find having the light gem here works best (esp when i want to check if standing on illumination (eg a charging pad etc)
but ive recently been testing without bottom and placing it above head, and using no GI 
trying to turn a emisive (light material function as cloud material) to mask the alpha as it will always be a positive technically as emissive. but thats a side note..

**Comment by r0b3rtf1sh3r** [comment]
![image](https://github.com/user-attachments/assets/ce3baeb6-9507-43a7-a058-4fbf7947976e)
i have it currently on 0.1 tick. if i set it to 0.25 (like the timer, there is a chance it will miss on frame and cause i have max 1 per frame will be forced to wait until next) microstutter is still their either way =)

**Comment by cem-akkaya** [comment]
I understand the component already needs some optimization during searching the value and reading the value from render target.  So in meantime will do that since it shouldn't make your render time go up dramatically up to 3x. 

Besides this you can leave tick interval of the component as it is since it doesn't do much things related to render thread. If you ask component to get light status , In that tick will go ask the scene capture component to read its values. So the tick over there doesn't really function

**Comment by r0b3rtf1sh3r** [comment]
yeah, thats what i may have noticed via testing, but not known exactly what to report. 
thanks. any thing else i can do to help let me know =)

**Comment by cem-akkaya** [comment]
made some updates here and there, and dig deep into a little bit more on lower level code of component.

Implemented 2 methods for you where you can choose on component as : Detection Method : Manuel / Update With Distance / Every Tick.

![image](https://github.com/user-attachments/assets/90603e6e-8c4b-459e-b475-8fd684ff4d3a)


On update with distance you can choose what would be delta distance to trigger capture event for light. like 10 units or more depending on your game. If not going to use that you can set it to manuel. 

Scene capture is now deferred and on these methods returning their value on next tick with event :

![image](https://github.com/user-attachments/assets/59186031-3952-4253-8a6c-067c88c9b180)


I was able to achive vsync 60 fps constant but you can test on yours and we can see what are the results. However RenderTargets interestingly very costly in unreal , so using the component wisely in that terms is important. You can lower sensitivity and use the delta distance method given.

There is also a new variable called "Light Update Step Threshold" this is usefull especiially if you want to ignore changes like 0.05 . If there is an update above that on tick event triggers.

Another advice with respect to not knowing your game. You can always ask component its status from subsystem rather than component constantly updating 

EX: 

1. Enemy senses trigger update event  sense (vision) 
2. Enemy accesses light awareness subsystem and finds sense target (us)
3. Enemy queries light status reaching a certain threshold and do more gameplay on it.

Please do not hesistate to contact me further about it, happy if it helps.

https://www.veed.io/view/f11d562d-98fd-4157-9aee-9b4993a427a1?panel=share

**Comment by r0b3rtf1sh3r** [comment]
so much to unpack here. the potential just increased crazy fold. my future projects will benefit from this greatly. 
especially from anyone wanting to make roguelike / 3PP / metal gear style games. wow 
sense trigger update threshold is outlook changer. this is great. 
update sense vision. mad. yeah find sense target. u knmow when u are hiding in the dark. and they cant see u . can control logic based on actual light movement so like being real sneaky , can read say "sneak variables vs the required level to avoid detection" . 
creepy dude touchin ya in the dark. "maniac alarm!"

**Comment by cem-akkaya** [comment]
I am happy that it helps and usefull. Definetly MGS stealth mechanics would benefit from this method a lot. It is not depending on time of the day, weather conditions or camera effects  but more likely depends on realtime illumination  which is quite unique method. Like in everything it has its down sides and upsides.

Please do test and reach me out if you have problems or further request that I can do with my limited knowledge. I can dig deeper maybe into rendering code and try to do it more efficient accessing buffer on the runtime.

You can potentially use this method for (in games)

- Stealth mechanics and ready check for attack/alert
- Reverse stealth mechanics, ai can stop/ non aggressive / non attacking state / if they are illuminated, flashlight or similar ( event with a torch in our case) EX: critters run away when area illuminated.
- Do auto activations : EX you go in case and after a certain treshold and check you light up your torch or flashlight.
- Do auto activations : Murals on cavern can only be seen in dark they are illuminated, that gives you a solution to a puzzle or quest location.
- Hiding in the bush can have sub mechanics as illumianated or not. Similar to sound/audio mechanics which many of the game do not consider since its found complex by developers possibly or costly. We can see those in many games assasin creed especially quite bad with it, elden ring is also bad but that game is nothing to do with stealth on overall game mechanics ^^
- AI Can follow illumination or react : Ex AI can be eager to follow illuminated areas in town. Non illuminated areas are less eager to be followed with AI and their behaviours can be different in both conditions. In non illuminated areas behavior types can be more shady types.
- Benefiting Not benefiting from light like regen (yours)
- Dynamic wold and with pcg knowing which areas in world before runtime and create a map for that. You can detect terrain show areas and grow moss over there or the plants growth rate can be higher lower depending on the light receive time factor.
- Dynamic wold : AI can know shadow areas to get a rest or cumulate. If there is an enemy creature that like shadows AI can place themselves there independent from time of day and weather conditions
- Technical art adjustments, making textures dynamically intensity adjusted depending on light conditions of that moment and place.
- Boss enounter mechanics : Lets imagine a boss in a cave, and Ogre , imagine Grull in wow. its "Udyr the Thousand Eyes" , can react to most illuminated area in raid including your VFX lights, raid has to switch regulary direction to avoid focused agro in order to slay the boss. If left in darkness Boss would regenerate health over time X per seconds. Which would be very challenging and very fun.
-Here is a new mechanic that I would like to see in games. BG3, Witcher, Elden ring.  You can rest anywhere and make camp, however if you pass time/sleep illumination matters. If you are in illuminated area sleeping you are less likely to get ambushed at night so its a preperation. Even can be used in some cases to reveal hidden bosses in open world games.
- Can go over many more new mechanics or existing mechanics thinked differently than tradional methods. Can achieve more dynamic results imo and only think you need is this and unreal.

Let me know and have a great day.

**Comment by r0b3rtf1sh3r** [comment]
still get a spike in stutter, i put it up to once every 5 seconds and manual. top only no gi. 
seems to have the least impact and almost not noticable.

**Comment by cem-akkaya** [comment]
Fair enough, happy that you get it working. As I said there can be really many use cases around it and it really depends how logic is implemented, however there would be even further optimisation methods, and as you know there is 5.5 coming up with megalights, i am pretty sure there is new methods implemented on rendering level that can be used as well in future (since I didn't check yet)

Still if you have problems around it I would be more than happy to help.

https://www.youtube.com/watch?v=7u75qSca0As

**Comment by r0b3rtf1sh3r** [comment]
100% _b

**Comment by r0b3rtf1sh3r** [comment]
with the addition of 5.5 and megalights . wonder if we will see a better response with performance. or newer techniques =)

**Comment by r0b3rtf1sh3r** [comment]
i tried to build for 5.5 but still assumes its for 5.4 is there an updated source build? (tried the other branches)

**Comment by cem-akkaya** [comment]
it shouldn't give build error afaik since I last checked but will look into it. Still should be fine to recompiled to 5.5

**Comment by r0b3rtf1sh3r** [comment]
i have forked your project and ima try and do some work on it or get some help to make it better 
i thought perhaps intigrating a incremental processing over many frames (to lighten the load) 
and perhaps variables or fab a way to control the resolution of the capture too =) 
idk. see what happens.

**Comment by cem-akkaya** [comment]
I checked in 5.5 again and I don't have any compilation errors, make sure you recompiling it and delete caches.

Sure go for it, feel free. You can make latent function and que processes. Let me know and feel free to send a pull request if you have something feasible.

**Comment by r0b3rtf1sh3r** [comment]
i think it may be some error on my part. im using autotool cause im lazy and visual studio was saying fail to compile but the result was 'success" in the log. . and would still think it was authored for previous to 5.5 version (would trigger on load ue5 proj file)
